var data = [
	{
		"title":"Thesis",
		"category":"University/Company",
		"small":"Tilt-based Reading Interactions",
		"image":["thesis.jpg"],
		"video":"",
		"github":"",
		"website":"http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1186482&dswid=4651",
		"desc":"This thesis was an explorative study aimed at the possibility of integrating tilt-based input to improve the reading experience on smartphones. Two experimental reading methods were designed, created and tested iteratively on 20, respectively 18 participants. The first method was a reassessment of tilt-based auto-scrolling and the second was a novel approach comparable to tilt-based paging. (The repository is unfortunatly private for the moment)",
		"date":"October 2017",
		"role":"Programming & Design",
		"tools":"Xcode",
		"duration":"2 months",
		"progress":"100%",
		"members":"Solo",
		"language":"Swift"
	},
	{
		"title":"SounDark",
		"category":"University",
		"small":"Audiobased Virtual Reality Game",
		"image":["soundark.png","soundark2.png","soundark3.png"],
		"video":"",
		"github":"https://github.com/Hubris37/Sonar",
		"website":"https://hubris37.github.io/Sonar/",
		"desc":"The project had the premise of traveling through a labyrinth in complete darkness, with the aid of ecolocalization. Riddled with patroling chesspieces, floating demon masks, doors that respond to certain pitches and crushing traps, this experience was meant to bewilder. An audience could view and participate in the game on a secondary screen through a topdown perspective using Wii-mote controllers. My task involved the implementation of gameplay, traps, interactable objects and procedural maze construction.",
		"date":"October 2016",
		"role":"Programming & Game Design",
		"tools":"Unity & Occulus",
		"duration":"5 weeks",
		"progress":"100%",
		"members":"6",
		"language":"C#"
	},
	{
		"title":"Jack-in-a-box",
		"category":"University",
		"small":"Haptic Horror Experiment",
		"image":["haptik4.png","haptik2.png","haptik3.png"],
		"video":"",
		"github":"https://github.com/apan1000/haptic-jack-in-the-box",
		"website":"",
		"desc":"The prototype consisted of a virtual jack-in-the-box which was hand cranked with a haptic device. Different effects for creating suspense were constructed using visual, audial and haptical techniques. The goal was to make the prototype seem as lifelike as possible through continually increasing resistance, gear simulations and an eerie soundtrack controlled by the motion of the crank. My task involved haptic interactions and minor graphics/cinematic effects.",
		"date":"April 2017",
		"role":"Programming",
		"tools":"Qt Creator & Novint Falcon",
		"duration":"3 weeks",
		"progress":"100%",
		"members":"3",
		"language":"C++"
	},
	{
		"title":"PapAR",
		"category":"University",
		"small":"Augmented Reality Mobile Application",
		"image":["papar.png"],
		"video":"https://vimeo.com/198999395",
		"github":"https://github.com/Ahlisen/pap-ar",
		"website":"",
		"desc":"The project was based on the idea of interacting with a magazine which was specifically printed for AR (By having helpful and intuitive markers). Using your phone as a lens allowed for the discovery of extra information and entertainment. These interactions ranged from voice-overs of articles to physics based simulations. The application was created to show the possibilites of augmented magazines. My task involved the implementation of Vuforia, sound, physics and general interactions.",
		"date":"December 2016",
		"role":"Programming & Sound",
		"tools":"Unity & Vuforia",
		"duration":"2 weeks",
		"progress":"100%",
		"members":"4",
		"language":"C#"
	},
	{
		"title":"bARk",
		"category":"University",
		"small":"Augmented Reality Mobile Application",
		"image":["bark.png"],
		"video":"",
		"github":"https://github.com/apan1000/bARk",
		"website":"https://apan1000.github.io/bARk/",
		"desc":"The application was an attempt at creating a fun and relaxing AR application with the purpose of watching procedurally generated trees grow through your smartphone. It was also possible to customize the shape of the leaves and the bark on the tree. My task involved L-systems and procedural generation of 3D meshes.",
		"date":"December 2016",
		"role":"Procedural Programming",
		"tools":"Unity & Vuforia",
		"duration":"3 weeks",
		"progress":"100%",
		"members":"6",
		"language":"C#"
	},
	{
		"title":"Equatorace",
		"category":"University",
		"small":"Nodebased Website",
		"image":["math.png","math2.png"],
		"video":"",
		"github":"https://gits-15.sys.kth.se/intnet17/mahlst-projekt",
		"website":"",
		"desc":"The aim for this project was to create a website where people could compete against eachother in increasingly difficult math problems. Web-sockets were utilized to create a realtime element where the player with the quickest mind and fastest fingers won. Supported up to 4 players simultaneously. Individual matches, highscores and accounts were stored using mySQL and encrypted with Scrypt.",
		"date":"February 2017",
		"role":"Programming",
		"tools":"AngularJS, Node.js & mySQL",
		"duration":"2 weeks",
		"progress":"100%",
		"members":"2",
		"language":"Javascript & mySQL"
	},
	{
		"title":"Symbiotic",
		"category":"Hobby",
		"small":"Competitive Multitasking",
		"image":["symbiotic.png","symbiotic2.png"],
		"video":"",
		"github":"https://github.com/Ahlisen/multi-tasking",
		"website":"",
		"desc":"Symbiotic was designed for 2-6 (or 4-12) players who take control of two creatures simultaneously: The reckless chaser and the deflecting prey. The chaser was put out of action if the partnering prey was captured, facilitating a need for continuous partial attention. The design I sought after was easy to learn and hard to master. Inspired by Achtung die kurve's ability to let a crowd of players cluster against a single screen.",
		"date":"January 2018",
		"role":"Programming, Art, Sound & Design",
		"tools":"Gamemaker Studio",
		"duration":"4 days",
		"progress":"75%",
		"members":"Solo",
		"language":"GML"
	},
	{
		"title":"Wintertrek",
		"category":"Hobby",
		"small":"Cooperative Sidescroller",
		"image":["doghuman.png"],
		"video":"",
		"github":"https://github.com/Ahlisen/frigid-side-scroller",
		"website":"",
		"desc":"Designed for 2 players who are trekking through the wilderness, facing beasts, lovecraftian monsters and harsh conditions - A dog and his human must cooperate to survive. Created to explore shaders, views inside views, asymmetrical gameplay and parallaxing backgrounds.",
		"date":"March 2017",
		"role":"Programming, Art, Sound & Design",
		"tools":"Gamemaker Studio",
		"duration":"5 days",
		"progress":"50%",
		"members":"Solo",
		"language":"GML"
	},
	{
		"title":"Henchmen",
		"category":"Hobby",
		"small":"Competitive Management",
		"image":["hench.png"],
		"video":"",
		"github":"https://github.com/Ahlisen/henchmen",
		"website":"",
		"desc":"Designed for 2-4 players. The game is a competition where each player is a leader commanding their henchmen to gather the most resources over a week. Inspired by a boardgame called 'Stone Age', the players must compete for limited labour availibilty, upgrade and feed their henchmen, or make a sacrifice to the old shrine! ",
		"date":"July 2016",
		"role":"Programming, Art, Sound & Design",
		"tools":"Gamemaker Studio",
		"duration":"7 days",
		"progress":"65%",
		"members":"Solo",
		"language":"GML"
	}
];